[profile.default]
solc = "0.8.19"
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ['NounScoutV2']
# via_ir = true
optimizer = true
optimizer_runs = 10000
[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/tree/master/config